/**
 * Public entry point for @supagloo/database-lib.
 *
 * Re-exports the generated Prisma client + types and the pinned PRISMA_VERSION.
 * Shared Zod schemas will be added here in later tasks.
 */
export { PRISMA_VERSION } from "./prisma-version";

// Driver-adapter client factory (Prisma 7 requires an adapter to connect).
export { createPrismaClient } from "./client";
export type { CreatePrismaClientOptions } from "./client";

// Application-level secrets encryption (design-delta §2.10). Shared primitive so
// API and DBOS encrypt/decrypt provider secrets the same way (AES-256-GCM).
export { encryptSecret, decryptSecret, SecretCryptoError } from "./secrets";
export type { SecretCryptoErrorCode } from "./secrets";

// Generated by `prisma generate` into src/generated/prisma (gitignored, built
// into dist/ by tsc). Provides PrismaClient, the Prisma namespace, model types,
// enums, and input types.
export * from "./generated/prisma/client";
