/**
 * Public entry point for @supagloo/database-lib.
 *
 * Re-exports the generated Prisma client + types and the pinned PRISMA_VERSION.
 * Shared Zod schemas will be added here in later tasks.
 */
export { PRISMA_VERSION } from "./prisma-version";

// Driver-adapter client factory (Prisma 7 requires an adapter to connect).
export { createPrismaClient } from "./client";
export type { CreatePrismaClientOptions } from "./client";

// Application-level secrets encryption (design-delta §2.10). Shared primitive so
// API and DBOS encrypt/decrypt provider secrets the same way (AES-256-GCM).
export { encryptSecret, decryptSecret, SecretCryptoError } from "./secrets";
export type { SecretCryptoErrorCode } from "./secrets";

// Shared GitHub App primitives (design-delta §2.3/§6a). App-JWT signing +
// installation-token minting, shared so API (callback verify + repo listing) and
// DBOS (git-ops workflows) use one implementation. Never persists a token.
export { signAppJwt, mintInstallationToken, GithubAppError } from "./github";
export type {
  GithubAppErrorCode,
  SignAppJwtOptions,
  MintInstallationTokenOptions,
  InstallationToken,
} from "./github";

// Shared S3 object-key layout helpers (design-delta §4/§8). One source of truth for
// the key format, shared by the writers (DBOS render/git-ops workflows) and the
// reader (the API's presigned-download route) so the format can never drift.
export {
  buildAssetKey,
  buildRenderOutputKey,
  buildRenderThumbnailKey,
  parseS3Key,
} from "./s3-keys";
export type { ParsedS3Key } from "./s3-keys";

// Shared domain Zod schemas (design-delta §2.11): LLM structured-output contracts,
// the supagloo.project.json manifest format, audio/render request shapes, and the
// Prisma-enum mirrors. Schema consts are `*Schema`-suffixed; inferred TS types use
// the bare names.
export * from "./schemas";

// Generated by `prisma generate` into src/generated/prisma (gitignored, built
// into dist/ by tsc). Provides PrismaClient, the Prisma namespace, model types,
// enums, and input types.
export * from "./generated/prisma/client";
